services:
  - type: web
    name: mediagrab-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_rest.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
